export const getSuccessAmountText = (amount: number, category: string) => `*${amount}₽* успешно занесено в *${category}*`;
export const amountEnteredWrongFormatText = '_Неправильное_ значение\n*Пример:* 120 Помидоры и огурцы';
export const selectCategoryText = 'Выбери категорию';
export const tryingAddDAmountText = '✍️Пытаюсь добавить данные✍️';
export const errorInCallbackQueryText = 'Ошибка в *callback_query*';
export const cacheIsEmptyText = 'Не нашелся обьект в кеше';
export const countrySheetChoiceText = 'Какая страна?';
export const armeniaSheetText = 'Армения';
export const russiaSheetText = 'Россия';
export const timeExpiredText = 'Я не дождалься, начни сначала';
